import { ImageProps } from 'react-native';

interface ImageIconProps extends ImageProps {
  square: number;
  circle: number;
  name:
    | 'PDF'
    | 'accommodation'
    | 'activity'
    | 'arrow'
    | 'at'
    | 'bookings'
    | 'calendar'
    | 'car'
    | 'clear'
    | 'clear_sky'
    | 'copy'
    | 'cross'
    | 'delete'
    | 'edit'
    | 'email'
    | 'few_clouds'
    | 'flight'
    | 'food_drink'
    | 'heart'
    | 'hide'
    | 'info'
    | 'invite'
    | 'link'
    | 'list'
    | 'location'
    | 'lock'
    | 'map'
    | 'messages_unread'
    | 'minus'
    | 'mist'
    | 'more'
    | 'more_class'
    | 'no_ads'
    | 'note'
    | 'notifications'
    | 'paperclip'
    | 'paperclipActive'
    | 'phone'
    | 'plus'
    | 'rail'
    | 'rain'
    | 'scattered_clouds_broken_clouds'
    | 'search'
    | 'settings'
    | 'show'
    | 'shower_rain_drizzle'
    | 'snow'
    | 'style'
    | 'thunderstorm'
    | 'tick'
    | 'travellers'
    | 'trips'
    | 'tripsActive'
    | 'username_email'
    | 'walk'
    | 'water'
    | 'weather_cloudy'
    | 'weather_humidity'
    | 'weather_partly_cloudy'
    | 'weather_rain'
    | 'weather_snow'
    | 'weather_storm'
    | 'weather_sun_shower'
    | 'weather_uv'
    | 'weather_wind'
    | 'whitePlus';
}

export default function ImageIcon(props: ImageIconProps): {};
